# -*- coding: utf-8 -*-
"""House_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yOdrAmBxWckqXyWY1d6cfrJiTR2Cv72h
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive/')

data=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Data/Housing.csv')

data.head()

data['driveway'] = data['driveway'].map({'yes': 1, 'no': 0})
data['recroom'] = data['recroom'].map({'yes': 1, 'no': 0})
data['fullbase'] = data['fullbase'].map({'yes': 1, 'no': 0})
data['gashw'] = data['gashw'].map({'yes': 1, 'no': 0})
data['airco'] = data['airco'].map({'yes': 1, 'no': 0})
data['prefarea'] = data['prefarea'].map({'yes': 1, 'no': 0})

data.head()

independent_varibales=data.columns
independent_varibales=independent_varibales.delete(0)
independent_varibales=independent_varibales.delete(0)
X=data[independent_varibales]
Y=data["price"]

import sklearn.linear_model as lm

lr=lm.LinearRegression()
lr.fit(X,Y)

independent_varibales

#Predict
user_info={}
for feature in independent_varibales:
  temp=input("Enter "+feature+": ")
  user_info[feature]=temp
  user_info_df=pd.DataFrame(data=user_info, index=[0], columns=independent_varibales)

price=lr.predict(user_info_df)
print(int(round(price[0])))

